"""Build the public "Réalisations" portfolio from the deployed sites.

Two outputs, regenerated on every deploy:

  1. A thumbnail screenshot per site at ``<slug>/assets/thumb.jpg`` — a snippet
     of the real, live page (above-the-fold capture via headless Chromium).
  2. A ``sites.json`` manifest at the repo root listing every deployed site
     (name, slug, category, url, thumb, date), newest first.

The landing page snippet and the standalone ``realisations.html`` gallery both
read ``sites.json`` at runtime, so they stay in sync automatically — no HTML is
ever regenerated by hand.

Usage:
    python -m pipeline.portfolio                # incremental: only new sites
    python -m pipeline.portfolio --force        # re-shoot every thumbnail
    python -m pipeline.portfolio --manifest-only   # skip screenshots
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

from . import config

THUMB_REL = "assets/thumb.jpg"          # relative to each site folder
MANIFEST_PATH = config.ROOT / "sites.json"
VIEWPORT = {"width": 1280, "height": 800}
THUMB_QUALITY = 70


def site_folders() -> list[Path]:
    """Root folders that are real generated sites (index.html + meta.json)."""
    out = []
    for p in sorted(config.ROOT.iterdir()):
        if not p.is_dir() or p.name.startswith("."):
            continue
        if p.name in config.RESERVED_SLUGS:
            continue
        if (p / "index.html").exists() and (p / "meta.json").exists():
            out.append(p)
    return out


def _needs_shot(folder: Path, force: bool) -> bool:
    thumb = folder / THUMB_REL
    if force or not thumb.exists():
        return True
    # Re-shoot only if the page changed after the last thumbnail.
    return (folder / "index.html").stat().st_mtime > thumb.stat().st_mtime


def screenshots(force: bool = False) -> int:
    """Capture an above-the-fold thumbnail for each site that needs one.

    Incremental by default: a site is skipped when its thumbnail is already
    newer than its index.html. Returns the number of thumbnails (re)generated.
    """
    from playwright.sync_api import sync_playwright

    pending = [f for f in site_folders() if _needs_shot(f, force)]
    if not pending:
        print("Thumbnails up to date — nothing to capture.")
        return 0

    print(f"Capturing {len(pending)} thumbnail(s)…")
    made = 0
    with sync_playwright() as pw:
        browser = pw.chromium.launch()
        page = browser.new_page(viewport=VIEWPORT, device_scale_factor=1)
        for i, folder in enumerate(pending, 1):
            thumb = folder / THUMB_REL
            thumb.parent.mkdir(parents=True, exist_ok=True)
            url = "file://" + str((folder / "index.html").resolve())
            try:
                page.goto(url, wait_until="load", timeout=20000)
                page.wait_for_timeout(1200)  # let fonts / CDN styles settle
                page.screenshot(
                    path=str(thumb), type="jpeg", quality=THUMB_QUALITY,
                    clip={"x": 0, "y": 0, **VIEWPORT},
                )
                made += 1
                print(f"  [{i}/{len(pending)}] {folder.name}")
            except Exception as e:  # noqa: BLE001 — one bad site must not stop the batch
                print(f"  [{i}/{len(pending)}] {folder.name} — SKIPPED ({type(e).__name__})")
        browser.close()
    return made


def build_manifest() -> int:
    """Write sites.json from every site's meta.json. Returns the site count."""
    sites = []
    for folder in site_folders():
        try:
            meta = json.loads((folder / "meta.json").read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        slug = meta.get("slug") or folder.name
        thumb = folder / THUMB_REL
        sites.append({
            "name": meta.get("name", slug),
            "slug": slug,
            "category": meta.get("category", "generic"),
            "url": f"{slug}/",
            "thumb": f"{slug}/{THUMB_REL}" if thumb.exists() else "",
            "generated_at": meta.get("generated_at", ""),
        })

    # Newest first; sites without a date sink to the bottom.
    sites.sort(key=lambda s: s["generated_at"] or "", reverse=True)

    payload = {
        "built_at": datetime.now().isoformat(timespec="seconds"),
        "count": len(sites),
        "sites": sites,
    }
    MANIFEST_PATH.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(f"Wrote {MANIFEST_PATH.name} — {len(sites)} site(s).")
    return len(sites)


def build(force: bool = False, manifest_only: bool = False) -> None:
    if not manifest_only:
        screenshots(force=force)
    build_manifest()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build the portfolio (thumbnails + manifest)")
    ap.add_argument("--force", action="store_true", help="re-shoot every thumbnail")
    ap.add_argument("--manifest-only", action="store_true", help="skip screenshots")
    args = ap.parse_args(argv)
    build(force=args.force, manifest_only=args.manifest_only)
    return 0


if __name__ == "__main__":
    sys.exit(main())
